/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.locagyn.visao;

import com.locagyn.enumeracao.TipoDeCliente;
import com.locagyn.modelos.Cliente;
import com.locagyn.modelos.Endereco;
import com.locagyn.modelos.Telefone;
import javax.swing.JOptionPane;
import com.locagyn.controle.ClienteControle;
import com.locagyn.controle.IClienteControle;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emill
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    IClienteControle clienteControle = new ClienteControle();

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
        this.setLocationRelativeTo(null);

        jTextFieldCPFCNPJ.setVisible(false);
        jTextFieldRazaoSocialNome.setVisible(false);
        jTextFieldIdentidade.setVisible(false);
        jLabelCPFCNPJ.setVisible(false);
        jLabelIdentidade.setVisible(false);
        jLabelRazaoSocialNome.setVisible(false);
        jTableCPF.getTableHeader().setReorderingAllowed(false);
        jTableCNPJ.getTableHeader().setReorderingAllowed(false);

        try {
            clienteControle.verTxt();

            imprimirTabela(clienteControle.listagem(TipoDeCliente.PESSOA_FISICA), TipoDeCliente.PESSOA_FISICA);
            imprimirTabela(clienteControle.listagem(TipoDeCliente.PESSOA_JURIDICA), TipoDeCliente.PESSOA_JURIDICA);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxTipoCliente = new javax.swing.JComboBox<>();
        jLabelCPFCNPJ = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldCPFCNPJ = new javax.swing.JTextField();
        jLabelRazaoSocialNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldRazaoSocialNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelIdentidade = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldIdentidade = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jLabelDdi = new javax.swing.JLabel();
        jTextFieldDDI = new javax.swing.JTextField();
        jLabelDdd = new javax.swing.JLabel();
        jTextFieldDDD = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelLogradouro = new javax.swing.JLabel();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCPF = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCNPJ = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemLocacao = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMotorista = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCategorias = new javax.swing.JMenuItem();
        jMenuItemCadastroDeAcessorios = new javax.swing.JMenuItem();
        jMenuItemCadastroVeiculo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCliente = new javax.swing.JMenuItem();
        jMenuItemCadastroDeModelo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMarca = new javax.swing.JMenuItem();
        jMenuItemTelaInicial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 198, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(896, 581));

        jComboBoxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel(TipoDeCliente.values()));
        jComboBoxTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoClienteActionPerformed(evt);
            }
        });

        jLabelCPFCNPJ.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelCPFCNPJ.setText("CPF:");

        jLabelTelefone.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelefone.setText("Telefone:");

        jTextFieldCPFCNPJ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldCPFCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCPFCNPJKeyTyped(evt);
            }
        });

        jLabelRazaoSocialNome.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelRazaoSocialNome.setText("Razão Social:");

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelEmail.setText("Email:");

        jTextFieldRazaoSocialNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelIdentidade.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelIdentidade.setText("Identidade:");

        jLabelEndereco.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereco.setText("Endereço:");

        jTextFieldIdentidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldIdentidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdentidadeKeyTyped(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAlterar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonIncluir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIncluir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonIncluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jLabelDdi.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelDdi.setText("DDI:");

        jTextFieldDDI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldDDI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDDIKeyTyped(evt);
            }
        });

        jLabelDdd.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelDdd.setText("DDD:");

        jTextFieldDDD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldDDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDDDKeyTyped(evt);
            }
        });

        jLabelNumero.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelNumero.setText("Número:");

        jTextFieldNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        jLabelLogradouro.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelLogradouro.setText("Logradouro:");

        jTextFieldLogradouro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelComplemento.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelComplemento.setText("Complemento:");

        jTextFieldComplemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelCEP.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelCEP.setText("CEP:");

        jTextFieldCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCEPKeyTyped(evt);
            }
        });

        jLabelBairro.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelBairro.setText("Bairro:");

        jTextFieldBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelEstado.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelEstado.setText("Estado:");

        jComboBoxEstado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabelCidade.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabelCidade.setText("Cidade:");

        jTextFieldCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableCPF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "Nome", "CPF", "IDENTIDADE", "EMAIL", "TELEFONE", "ENDEREÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCPF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCPF.setGridColor(new java.awt.Color(0, 0, 0));
        jTableCPF.setShowGrid(true);
        jTableCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCPFMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCPF);

        jTableCNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableCNPJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "Razao Social", "CNPJ", "EMAIL", "TELEFONE", "ENDERECO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCNPJ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCNPJ.setGridColor(new java.awt.Color(0, 0, 0));
        jTableCNPJ.setShowGrid(true);
        jTableCNPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCNPJMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCNPJ);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCPFCNPJ)
                                    .addComponent(jLabelDdi)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelDdd)
                                    .addComponent(jLabelNumero))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabelRazaoSocialNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldRazaoSocialNome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62)
                                                .addComponent(jLabelIdentidade)
                                                .addGap(3, 3, 3)
                                                .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabelComplemento)
                                                            .addComponent(jLabelBairro)
                                                            .addComponent(jLabelCidade)
                                                            .addComponent(jLabelLogradouro))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextFieldLogradouro)
                                                            .addComponent(jTextFieldComplemento)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                    .addComponent(jTextFieldCidade)
                                                                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                                        .addComponent(jButtonIncluir)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jButtonAlterar))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabelEstado)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabelCEP)
                                                                                .addGap(32, 32, 32)))
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jTextFieldCEP)
                                                                            .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addGap(686, 686, 686)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPFCNPJ)
                    .addComponent(jLabelRazaoSocialNome)
                    .addComponent(jTextFieldRazaoSocialNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdentidade)
                    .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDdi)
                    .addComponent(jTextFieldDDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDdd)
                    .addComponent(jTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComplemento)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCEP)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jMenuOpcoes.setText("Options");

        jMenuItemLocacao.setText("Locação");
        jMenuItemLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocacaoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemLocacao);

        jMenuItemCadastroDeMotorista.setText("Cadastro de Motorista");
        jMenuItemCadastroDeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMotoristaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMotorista);

        jMenuItemCadastroDeCategorias.setText("Cadastro de Categorias");
        jMenuItemCadastroDeCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeCategoriasActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCategorias);

        jMenuItemCadastroDeAcessorios.setText("Cadastro de Acessorios");
        jMenuItemCadastroDeAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeAcessoriosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeAcessorios);

        jMenuItemCadastroVeiculo.setText("Cadastro de Veículo");
        jMenuItemCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVeiculoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroVeiculo);

        jMenuItemCadastroDeCliente.setText("Cadastro de Cliente");
        jMenuItemCadastroDeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeClienteActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCliente);

        jMenuItemCadastroDeModelo.setText("Cadastro de Modelo");
        jMenuItemCadastroDeModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeModeloActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeModelo);

        jMenuItemCadastroDeMarca.setText("Cadastro de Marca");
        jMenuItemCadastroDeMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMarcaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMarca);

        jMenuItemTelaInicial.setText("Tela Inicial");
        jMenuItemTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaInicialActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemTelaInicial);

        jMenuBar1.add(jMenuOpcoes);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherComboboxCliente() {
        jComboBoxTipoCliente.removeAllItems();

    }

    public void imprimirTabela(ArrayList<Cliente> listadecliente, TipoDeCliente tipoDeCliente) {
        try {

            if (tipoDeCliente.equals(TipoDeCliente.PESSOA_FISICA)) {

                DefaultTableModel tabela = (DefaultTableModel) jTableCPF.getModel();
                tabela.setNumRows(0);
                Iterator<Cliente> lista = listadecliente.iterator();
                //String saida = " " + listadecliente.get(0).getNome() + "\n" + listadecliente.get(1).getNome()+
                //        "\n " + listadecliente.get(2).getNome();
                //JOptionPane.showMessageDialog(this, saida + " " );
                while (lista.hasNext()) {
                    String[] tab = new String[7];
                    Cliente aux = lista.next();
                    tab[0] = aux.getId() + "";
                    tab[1] = aux.getNome();
                    tab[2] = aux.getCpf();
                    tab[3] = aux.getIdentidade();
                    tab[4] = aux.getEmail();
                    tab[5] = aux.getTelefone().toString();
                    tab[6] = aux.getEndereco().toString();

                    tabela.addRow(tab);
                }

            }
            if (tipoDeCliente.equals(TipoDeCliente.PESSOA_JURIDICA)) {

                DefaultTableModel tabela = (DefaultTableModel) jTableCNPJ.getModel();
                tabela.setNumRows(0);
                Iterator<Cliente> lista = listadecliente.iterator();

                while (lista.hasNext()) {
                    String[] tab = new String[6];
                    Cliente aux = lista.next();
                    tab[0] = aux.getId() + "";
                    tab[1] = aux.getRazaoSocial();
                    tab[2] = aux.getCnpj();
                    tab[3] = aux.getEmail();
                    tab[4] = aux.getTelefone().toString();
                    tab[5] = aux.getEndereco().toString();

                    tabela.addRow(tab);
                }

            }
            /*DefaultTableModel tabela = (DefaultTableModel) jTablecpf.getModel();
            tabela.setNumRows(0);
            Iterator<Cliente> lista = listadecliente.iterator();

            while (lista.hasNext()) {
                String[] tab = new String[4];
                Cliente aux = lista.next();
                tab[0] = aux.getId() + "";
                tab[1] = aux.getNome();
                tab[2] = aux.getCpf();
                tab[3] = aux.getEmail();
                tab[4] = aux.getTelefone().toString();

                tabela.addRow(tab);
            }*/
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:

        try {

            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {

                long ddi = Long.parseLong(jTextFieldDDI.getText());
                long ddd = Long.parseLong(jTextFieldDDD.getText());
                long numero = Long.parseLong(jTextFieldNumero.getText());
                Telefone telefone = new Telefone(ddi, ddd, numero);

                //captando endereco
                String logradouro = jTextFieldLogradouro.getText();
                String complemento = jTextFieldComplemento.getText();
                String bairro = jTextFieldBairro.getText();
                String cidade = jTextFieldCidade.getText();
                String estado = jComboBoxEstado.getSelectedItem().toString();
                long cep = Long.parseLong(jTextFieldCEP.getText());
                Endereco endereco = new Endereco(logradouro, complemento, cidade, estado, bairro, cep);
                String xxx = jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 0).toString();
                Cliente clientepf = new Cliente(Integer.parseInt(xxx), jTextFieldCPFCNPJ.getText(), jTextFieldRazaoSocialNome.getText(), jTextFieldIdentidade.getText(), jTextFieldEmail.getText(), telefone, endereco, TipoDeCliente.PESSOA_FISICA);
                clienteControle.alterar(clientepf, TipoDeCliente.PESSOA_FISICA);
                imprimirTabela(clienteControle.listagem(TipoDeCliente.PESSOA_FISICA), TipoDeCliente.PESSOA_FISICA);

            }

            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_JURIDICA)) {

                long ddi = Long.parseLong(jTextFieldDDI.getText());
                long ddd = Long.parseLong(jTextFieldDDD.getText());
                long numero = Long.parseLong(jTextFieldNumero.getText());
                Telefone telefone = new Telefone(ddi, ddd, numero);

                //captando endereco
                String logradouro = jTextFieldLogradouro.getText();
                String complemento = jTextFieldComplemento.getText();
                String bairro = jTextFieldBairro.getText();
                String cidade = jTextFieldCidade.getText();
                String estado = jComboBoxEstado.getSelectedItem().toString();
                long cep = Long.parseLong(jTextFieldCEP.getText());
                Endereco endereco = new Endereco(logradouro, complemento, cidade, estado, bairro, cep);

                Cliente clientepj = new Cliente(Integer.parseInt(jTableCNPJ.getValueAt(jTableCNPJ.getSelectedRow(), 0).toString()), jTextFieldCPFCNPJ.getText(), jTextFieldRazaoSocialNome.getText(), jTextFieldEmail.getText(), telefone, endereco, TipoDeCliente.PESSOA_JURIDICA);
                clienteControle.alterar(clientepj, TipoDeCliente.PESSOA_JURIDICA);
                imprimirTabela(clienteControle.listagem(TipoDeCliente.PESSOA_JURIDICA), TipoDeCliente.PESSOA_JURIDICA);

            }

            //Cliente clientepj = new Cliente(0, jTextFieldCPFCNPJ.getText(), jTextFieldRazaoSocialNome.getText(), jTextFieldEmail.getText(), telefone, endereco, TipoDeCliente.PESSOA_JURIDICA);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed


    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:

        //Botão incluir
        try {

            //Verificação combobox e inclusao
            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.SELECIONE)) {
                throw new Exception("Selecione o tipo do cliente!");
            }

            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {
                //captando telefone

                long ddi = Long.parseLong(jTextFieldDDI.getText());
                long ddd = Long.parseLong(jTextFieldDDD.getText());
                long numero = Long.parseLong(jTextFieldNumero.getText());
                Telefone telefone = new Telefone(ddi, ddd, numero);

                //captando endereco
                String logradouro = jTextFieldLogradouro.getText();
                String complemento = jTextFieldComplemento.getText();
                String bairro = jTextFieldBairro.getText();
                String cidade = jTextFieldCidade.getText();
                String estado = jComboBoxEstado.getSelectedItem().toString();
                long cep = Long.parseLong(jTextFieldCEP.getText());
                Endereco endereco = new Endereco(logradouro, complemento, cidade, estado, bairro, cep);

                Cliente clientepf = new Cliente(0, jTextFieldCPFCNPJ.getText(), jTextFieldRazaoSocialNome.getText(), jTextFieldIdentidade.getText(), jTextFieldEmail.getText(), telefone, endereco, TipoDeCliente.PESSOA_FISICA);
                clienteControle.incluir(clientepf, TipoDeCliente.PESSOA_FISICA);
                imprimirTabela(clienteControle.listagem(TipoDeCliente.PESSOA_FISICA), TipoDeCliente.PESSOA_FISICA);
                /*jTextFieldCPFCNPJ.setText("");
                jTextFieldIdentidade.setText("");
                jTextFieldEmail.setText("");
                jTextFieldRazaoSocialNome.setText("");
                 */
            }

            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_JURIDICA)) {
                //captando telefone
                long ddi = Long.parseLong(jTextFieldDDI.getText());
                long ddd = Long.parseLong(jTextFieldDDD.getText());
                long numero = Long.parseLong(jTextFieldNumero.getText());
                Telefone telefone = new Telefone(ddi, ddd, numero);

                //captando endereco
                String logradouro = jTextFieldLogradouro.getText();
                String complemento = jTextFieldComplemento.getText();
                String bairro = jTextFieldBairro.getText();
                String cidade = jTextFieldCidade.getText();
                String estado = jComboBoxEstado.getSelectedItem().toString();
                long cep = Long.parseLong(jTextFieldCEP.getText());
                Endereco endereco = new Endereco(logradouro, complemento, cidade, estado, bairro, cep);

                Cliente clientepj = new Cliente(0, jTextFieldCPFCNPJ.getText(), jTextFieldRazaoSocialNome.getText(), jTextFieldEmail.getText(), telefone, endereco, TipoDeCliente.PESSOA_JURIDICA);
                clienteControle.incluir(clientepj, TipoDeCliente.PESSOA_JURIDICA);
                imprimirTabela(clienteControle.listagem(TipoDeCliente.PESSOA_JURIDICA), TipoDeCliente.PESSOA_JURIDICA);
                /*
                jTextFieldEmail.setText("");
                 */
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }


    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jComboBoxTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoClienteActionPerformed
        // TODO add your handling code here:

        if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.SELECIONE)) {
            jLabelCPFCNPJ.setVisible(false);
            jLabelIdentidade.setVisible(false);
            jLabelRazaoSocialNome.setVisible(false);
            jTextFieldCPFCNPJ.setVisible(false);
            jTextFieldIdentidade.setVisible(false);
            jTextFieldRazaoSocialNome.setVisible(false);
            jLabelEndereco.setVisible(true);
            jLabelComplemento.setVisible(true);
            jLabelLogradouro.setVisible(true);
            jLabelBairro.setVisible(true);
            jLabelCEP.setVisible(true);
            jLabelEstado.setVisible(true);
            jComboBoxEstado.setVisible(true);
            jLabelCidade.setVisible(true);
            jTextFieldCEP.setVisible(true);
            jTextFieldBairro.setVisible(true);
            jTextFieldCidade.setVisible(true);
            jTextFieldComplemento.setVisible(true);
            jTextFieldLogradouro.setVisible(true);
            jLabelNumero.setVisible(true);
            jLabelDdd.setVisible(true);
            jLabelDdi.setVisible(true);
            jLabelNumero.setVisible(true);
            jTextFieldDDD.setVisible(true);
            jTextFieldDDI.setVisible(true);
            jTextFieldNumero.setVisible(true);
        }

        if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {
            jLabelCPFCNPJ.setVisible(true);
            jLabelCPFCNPJ.setText("CPF:");
            jLabelIdentidade.setVisible(true);
            jLabelRazaoSocialNome.setVisible(true);
            jLabelRazaoSocialNome.setText("Nome:");
            jTextFieldCPFCNPJ.setVisible(true);
            jTextFieldRazaoSocialNome.setVisible(true);
            jTextFieldIdentidade.setVisible(true);
            jLabelEndereco.setVisible(true);
            jLabelComplemento.setVisible(true);
            jLabelLogradouro.setVisible(true);
            jLabelBairro.setVisible(true);
            jLabelCEP.setVisible(true);
            jLabelEstado.setVisible(true);
            jComboBoxEstado.setVisible(true);
            jLabelCidade.setVisible(true);
            jTextFieldCEP.setVisible(true);
            jTextFieldBairro.setVisible(true);
            jTextFieldCidade.setVisible(true);
            jTextFieldComplemento.setVisible(true);
            jTextFieldLogradouro.setVisible(true);
            jLabelNumero.setVisible(true);
            jLabelDdd.setVisible(true);
            jLabelDdi.setVisible(true);
            jLabelNumero.setVisible(true);
            jTextFieldDDD.setVisible(true);
            jTextFieldDDI.setVisible(true);
            jTextFieldNumero.setVisible(true);
            //jTableCNPJ.setVisible(false);
            //jTableCPF.setVisible(true);
        }

        if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_JURIDICA)) {
            jLabelCPFCNPJ.setVisible(true);
            jLabelCPFCNPJ.setText("CNPJ:");
            jLabelIdentidade.setVisible(false);
            jLabelRazaoSocialNome.setVisible(true);
            jLabelRazaoSocialNome.setText("Razão Social:");
            jTextFieldCPFCNPJ.setVisible(true);
            jTextFieldIdentidade.setVisible(false);
            jLabelEndereco.setVisible(true);
            jLabelComplemento.setVisible(true);
            jLabelLogradouro.setVisible(true);
            jLabelBairro.setVisible(true);
            jLabelCEP.setVisible(true);
            jLabelEstado.setVisible(true);
            jComboBoxEstado.setVisible(true);
            jLabelCidade.setVisible(true);
            jTextFieldCEP.setVisible(true);
            jTextFieldBairro.setVisible(true);
            jTextFieldCidade.setVisible(true);
            jTextFieldComplemento.setVisible(true);
            jTextFieldLogradouro.setVisible(true);
            jLabelNumero.setVisible(true);
            jLabelDdd.setVisible(true);
            jLabelDdi.setVisible(true);
            jLabelNumero.setVisible(true);
            jTextFieldDDD.setVisible(true);
            jTextFieldDDI.setVisible(true);
            jTextFieldNumero.setVisible(true);
            //jTableCNPJ.setVisible(true);
            //jTableCPF.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxTipoClienteActionPerformed

    private void jTableCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCPFMouseClicked
        // TODO add your handling code here:

        try {

            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {
                jTextFieldRazaoSocialNome.setText(jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 1).toString());
                jTextFieldCPFCNPJ.setText(jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 2).toString());
                jTextFieldIdentidade.setText(jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 3).toString());
                jTextFieldEmail.setText(jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 4).toString());

                String telefoneTodo = jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 5).toString();
                String[] telefoneSplit = telefoneTodo.split(";");

                jTextFieldDDI.setText(telefoneSplit[0]);
                jTextFieldDDD.setText(telefoneSplit[1]);
                jTextFieldNumero.setText(telefoneSplit[2]);

                String enderecoTodo = jTableCPF.getValueAt(jTableCPF.getSelectedRow(), 6).toString();
                String[] enderecoSplit = enderecoTodo.split(";");

                jTextFieldLogradouro.setText(enderecoSplit[0]);
                jTextFieldComplemento.setText(enderecoSplit[1]);
                jTextFieldBairro.setText(enderecoSplit[2]);
                jTextFieldCidade.setText(enderecoSplit[3]);

                for (int i = 0; i < 26; i++) {

                    if (enderecoSplit[4].equals(jComboBoxEstado.getItemAt(i))) {
                        jComboBoxEstado.setSelectedIndex(i);
                    }
                }

                jTextFieldCEP.setText(enderecoSplit[5]);

                System.out.println(jTableCPF.getSelectedRow() + " " + jTableCPF.getSelectedColumn());
            }
            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_JURIDICA)) {
                throw new Exception("Antes de Selecionar algum cliente físico selecione o tipo de cliente físico.");
            } else if(jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.SELECIONE)){
                throw new Exception("Selecione um tipo de cliente");
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jTableCPFMouseClicked

    private void jTableCNPJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCNPJMouseClicked
        // TODO add your handling code here:
        try {

            if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_JURIDICA)) {
                jTextFieldRazaoSocialNome.setText(jTableCNPJ.getValueAt(jTableCNPJ.getSelectedRow(), 1).toString());
                jTextFieldCPFCNPJ.setText(jTableCNPJ.getValueAt(jTableCNPJ.getSelectedRow(), 2).toString());
                jTextFieldEmail.setText(jTableCNPJ.getValueAt(jTableCNPJ.getSelectedRow(), 3).toString());

                String telefoneTodo = jTableCNPJ.getValueAt(jTableCNPJ.getSelectedRow(), 4).toString();
                String[] telefoneSplit = telefoneTodo.split(";");

                jTextFieldDDI.setText(telefoneSplit[0]);
                jTextFieldDDD.setText(telefoneSplit[1]);
                jTextFieldNumero.setText(telefoneSplit[2]);

                String enderecoTodo = jTableCNPJ.getValueAt(jTableCNPJ.getSelectedRow(), 5).toString();
                String[] enderecoSplit = enderecoTodo.split(";");

                jTextFieldLogradouro.setText(enderecoSplit[0]);
                jTextFieldComplemento.setText(enderecoSplit[1]);
                jTextFieldBairro.setText(enderecoSplit[2]);
                jTextFieldCidade.setText(enderecoSplit[3]);

                for (int i = 0; i < 26; i++) {

                    if (enderecoSplit[4].equals(jComboBoxEstado.getItemAt(i))) {
                        jComboBoxEstado.setSelectedIndex(i);
                    }
                }

                jTextFieldCEP.setText(enderecoSplit[5]);

            } else if (jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {
                throw new Exception("Antes de Selecionar algum cliente PJ selecione o tipo de cliente PJ.");
            } else if(jComboBoxTipoCliente.getSelectedItem().equals(TipoDeCliente.SELECIONE)){
                throw new Exception("Selecione um tipo de cliente");
            }
            System.out.println(jTableCNPJ.getSelectedRow() + " " + jTableCNPJ.getSelectedColumn());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jTableCNPJMouseClicked

    private void jMenuItemLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocacaoActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeLocacao telaLocacao = new TelaDeLocacao();
            telaLocacao.setLocationRelativeTo(null);
            telaLocacao.setVisible(true);
            this.setVisible(false);
            telaLocacao.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemLocacaoActionPerformed

    private void jMenuItemCadastroDeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMotoristaActionPerformed
        // TODO add your handling code here:
        try {
            TelaCadastroMotorista telaMotorista = new TelaCadastroMotorista();
            telaMotorista.setLocationRelativeTo(null);
            telaMotorista.setVisible(true);
            this.setVisible(false);
            telaMotorista.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMotoristaActionPerformed

    private void jMenuItemCadastroDeCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeCategoriasActionPerformed
        // TODO add your handling code here:
        try {

            TelaDeCategoria telaCategoria = new TelaDeCategoria();
            telaCategoria.setLocationRelativeTo(null);
            telaCategoria.setVisible(true);
            this.setVisible(false);
            telaCategoria.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeCategoriasActionPerformed

    private void jMenuItemCadastroDeAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeAcessoriosActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeAcessorios telaAcessorios = new TelaDeAcessorios();
            telaAcessorios.setLocationRelativeTo(null);
            telaAcessorios.setVisible(true);
            this.setVisible(false);
            telaAcessorios.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeAcessoriosActionPerformed

    private void jMenuItemCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVeiculoActionPerformed
        // TODO add your handling code here:
        try {

            TelaCadastroVeiculo telaVeiculo = new TelaCadastroVeiculo();
            telaVeiculo.setLocationRelativeTo(null);
            telaVeiculo.setVisible(true);
            this.setVisible(false);
            telaVeiculo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroVeiculoActionPerformed

    private void jMenuItemCadastroDeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeClienteActionPerformed
        // TODO add your handling code here:
        try {

            TelaCadastroCliente cadastroCliente = new TelaCadastroCliente();
            cadastroCliente.setLocationRelativeTo(null);
            cadastroCliente.setVisible(true);
            this.setVisible(false);
            cadastroCliente.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeClienteActionPerformed

    private void jMenuItemCadastroDeModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeModeloActionPerformed
        // TODO add your handling code here:
        try {
            TelaDosModelos telaModelo = new TelaDosModelos();
            telaModelo.setLocationRelativeTo(null);
            telaModelo.setVisible(true);
            this.setVisible(false);
            telaModelo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeModeloActionPerformed

    private void jMenuItemCadastroDeMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMarcaActionPerformed
        // TODO add your handling code here:
        try {

            TelaDasMarcas telaMarca = new TelaDasMarcas();
            telaMarca.setLocationRelativeTo(null);
            telaMarca.setVisible(true);
            this.setVisible(false);
            telaMarca.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMarcaActionPerformed

    private void jMenuItemTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaInicialActionPerformed
        // TODO add your handling code here:
        try {

            TelaInicial telaInicial = new TelaInicial();
            telaInicial.setLocationRelativeTo(null);
            telaInicial.setVisible(true);
            this.setVisible(false);
            telaInicial.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemTelaInicialActionPerformed

    private void jTextFieldDDIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDDIKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDDIKeyTyped

    private void jTextFieldDDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDDDKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDDDKeyTyped

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldCPFCNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPFCNPJKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCPFCNPJKeyTyped

    private void jTextFieldIdentidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentidadeKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIdentidadeKeyTyped

    private void jTextFieldCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCEPKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCEPKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxTipoCliente;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPFCNPJ;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelDdd;
    private javax.swing.JLabel jLabelDdi;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelIdentidade;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRazaoSocialNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroDeAcessorios;
    private javax.swing.JMenuItem jMenuItemCadastroDeCategorias;
    private javax.swing.JMenuItem jMenuItemCadastroDeCliente;
    private javax.swing.JMenuItem jMenuItemCadastroDeMarca;
    private javax.swing.JMenuItem jMenuItemCadastroDeModelo;
    private javax.swing.JMenuItem jMenuItemCadastroDeMotorista;
    private javax.swing.JMenuItem jMenuItemCadastroVeiculo;
    private javax.swing.JMenuItem jMenuItemLocacao;
    private javax.swing.JMenuItem jMenuItemTelaInicial;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableCNPJ;
    private javax.swing.JTable jTableCPF;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPFCNPJ;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldDDD;
    private javax.swing.JTextField jTextFieldDDI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentidade;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRazaoSocialNome;
    // End of variables declaration//GEN-END:variables
}
