/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.locagyn.visao;

import com.locagyn.controle.IDevolucaoControle;
import com.locagyn.controle.ILocacaoControle;
import com.locagyn.controle.LocacaoControle;
import com.locagyn.enumeracao.SituacaoLocacao;
import com.locagyn.modelos.Devolucao;
import com.locagyn.modelos.Locacao;
import com.locagyn.controle.DevolucaoControle;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author emill
 */
public class TelaDevolucao extends javax.swing.JFrame {

    ILocacaoControle locacaoControle = new LocacaoControle();
    IDevolucaoControle devolucaoControle = new DevolucaoControle();
    String anexo1;
    String anexo2;
    String anexo3;
    String anexo4;

    /**
     * Creates new form TelaDevolucao
     */
    public TelaDevolucao() {
        initComponents();
        jTextFieldTanqueCheio.setEnabled(false);
        jTextFieldDiasAMais.setEnabled(false);
        jTextFieldValorDano.setEnabled(false);
        jTextFieldValorSujo.setEnabled(false);
        jTextFieldDiasAMenos.setEnabled(false);
        jTextFieldTotal.setEnabled(false);
        jTextFieldTotal.setEditable(false);
        

        try {
            ArrayList<Locacao> listaLocacao = locacaoControle.listagem();

            String[] listaCombo = new String[listaLocacao.size()];
            for (int pos = 0; pos < listaLocacao.size(); pos++) {
                listaCombo[pos] = listaLocacao.get(pos).getDataInicio();
                jComboBoxLocacao.addItem(listaCombo[pos]);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha ao carregar combobox. Verifique!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldKm = new javax.swing.JTextField();
        jCheckBoxLocacaoAMaisTempo = new javax.swing.JCheckBox();
        jCheckBoxLocacaoAMenosTempo = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldValorDano = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldDiasAMais = new javax.swing.JTextField();
        jCheckBoxDanoSofrido = new javax.swing.JCheckBox();
        jCheckBoxLimpeza = new javax.swing.JCheckBox();
        jCheckBoxTanqueCheio = new javax.swing.JCheckBox();
        jTextFieldAnexo2 = new javax.swing.JLabel();
        jTextFieldAnexo3 = new javax.swing.JLabel();
        jTextFieldAnexo4 = new javax.swing.JLabel();
        jTextFieldAnexo1 = new javax.swing.JLabel();
        jButtonAnexo1 = new javax.swing.JButton();
        jButtonAnexo2 = new javax.swing.JButton();
        jButtonAnexo3 = new javax.swing.JButton();
        jButtonAnexo4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxLocacao = new javax.swing.JComboBox<>();
        jButtonDevolver = new javax.swing.JButton();
        jTextFieldDiasAMenos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldValorSujo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldTanqueCheio = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemLocacao = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMotorista = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCategorias = new javax.swing.JMenuItem();
        jMenuItemCadastroDeAcessorios = new javax.swing.JMenuItem();
        jMenuItemCadastroVeiculo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCliente = new javax.swing.JMenuItem();
        jMenuItemCadastroDeModelo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMarca = new javax.swing.JMenuItem();
        jMenuItemTelaInicial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 198, 238));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Km:");

        jTextFieldKm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldKmKeyTyped(evt);
            }
        });

        jCheckBoxLocacaoAMaisTempo.setBackground(new java.awt.Color(176, 198, 238));
        jCheckBoxLocacaoAMaisTempo.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jCheckBoxLocacaoAMaisTempo.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxLocacaoAMaisTempo.setText("Veículo locado a mais tempo");
        jCheckBoxLocacaoAMaisTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLocacaoAMaisTempoActionPerformed(evt);
            }
        });

        jCheckBoxLocacaoAMenosTempo.setBackground(new java.awt.Color(176, 198, 238));
        jCheckBoxLocacaoAMenosTempo.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jCheckBoxLocacaoAMenosTempo.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxLocacaoAMenosTempo.setText("Veículo locado a menos tempo");
        jCheckBoxLocacaoAMenosTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLocacaoAMenosTempoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Dias a mais:");

        jTextFieldValorDano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorDanoActionPerformed(evt);
            }
        });
        jTextFieldValorDano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorDanoKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Dias a menos:");

        jTextFieldDiasAMais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiasAMaisKeyTyped(evt);
            }
        });

        jCheckBoxDanoSofrido.setBackground(new java.awt.Color(176, 198, 238));
        jCheckBoxDanoSofrido.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jCheckBoxDanoSofrido.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxDanoSofrido.setText("Veículo sofreu algum dano");
        jCheckBoxDanoSofrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDanoSofridoActionPerformed(evt);
            }
        });

        jCheckBoxLimpeza.setBackground(new java.awt.Color(176, 198, 238));
        jCheckBoxLimpeza.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jCheckBoxLimpeza.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxLimpeza.setText("Veículo sujo");
        jCheckBoxLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLimpezaActionPerformed(evt);
            }
        });

        jCheckBoxTanqueCheio.setBackground(new java.awt.Color(176, 198, 238));
        jCheckBoxTanqueCheio.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jCheckBoxTanqueCheio.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxTanqueCheio.setText("Veículo com tanque cheio");
        jCheckBoxTanqueCheio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTanqueCheioActionPerformed(evt);
            }
        });

        jTextFieldAnexo2.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldAnexo2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jTextFieldAnexo3.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldAnexo3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jTextFieldAnexo4.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldAnexo4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jTextFieldAnexo1.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldAnexo1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButtonAnexo1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAnexo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAnexo1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnexo1.setText("Anexo 1");
        jButtonAnexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnexo1ActionPerformed(evt);
            }
        });

        jButtonAnexo2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAnexo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAnexo2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnexo2.setText("Anexo 2");
        jButtonAnexo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnexo2ActionPerformed(evt);
            }
        });

        jButtonAnexo3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAnexo3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAnexo3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnexo3.setText("Anexo 3");
        jButtonAnexo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnexo3ActionPerformed(evt);
            }
        });

        jButtonAnexo4.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAnexo4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAnexo4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnexo4.setText("Anexo 4");
        jButtonAnexo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnexo4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Locação:");

        jComboBoxLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLocacaoActionPerformed(evt);
            }
        });

        jButtonDevolver.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDevolver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonDevolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jTextFieldDiasAMenos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiasAMenosKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Valor:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Total:");

        jTextFieldValorSujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorSujoActionPerformed(evt);
            }
        });
        jTextFieldValorSujo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorSujoKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Valor:");

        jTextFieldTanqueCheio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTanqueCheioActionPerformed(evt);
            }
        });
        jTextFieldTanqueCheio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTanqueCheioKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Valor:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Hora:");

        jTextFieldHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraActionPerformed(evt);
            }
        });
        jTextFieldHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHoraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDevolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel23))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCheckBoxLimpeza)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDiasAMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxLocacaoAMenosTempo)
                            .addComponent(jCheckBoxLocacaoAMaisTempo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDiasAMais, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxDanoSofrido)
                            .addComponent(jCheckBoxTanqueCheio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTanqueCheio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldValorSujo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldValorDano, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAnexo3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAnexo2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonAnexo1)
                                            .addComponent(jButtonAnexo2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jButtonAnexo3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jButtonAnexo4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jTextFieldAnexo4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAnexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnexo2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAnexo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnexo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnexo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnexo4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAnexo3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnexo4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDevolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jComboBoxLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxLocacaoAMaisTempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldDiasAMais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxLocacaoAMenosTempo)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDiasAMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxDanoSofrido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValorDano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(13, 13, 13)
                        .addComponent(jCheckBoxLimpeza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValorSujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxTanqueCheio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldTanqueCheio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addComponent(jLabel21))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenuOpcoes.setText("Options");

        jMenuItemLocacao.setText("Locação");
        jMenuItemLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocacaoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemLocacao);

        jMenuItemCadastroDeMotorista.setText("Cadastro de Motorista");
        jMenuItemCadastroDeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMotoristaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMotorista);

        jMenuItemCadastroDeCategorias.setText("Cadastro de Categorias");
        jMenuItemCadastroDeCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeCategoriasActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCategorias);

        jMenuItemCadastroDeAcessorios.setText("Cadastro de Acessorios");
        jMenuItemCadastroDeAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeAcessoriosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeAcessorios);

        jMenuItemCadastroVeiculo.setText("Cadastro de Veículo");
        jMenuItemCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVeiculoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroVeiculo);

        jMenuItemCadastroDeCliente.setText("Cadastro de Cliente");
        jMenuItemCadastroDeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeClienteActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCliente);

        jMenuItemCadastroDeModelo.setText("Cadastro de Modelo");
        jMenuItemCadastroDeModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeModeloActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeModelo);

        jMenuItemCadastroDeMarca.setText("Cadastro de Marca");
        jMenuItemCadastroDeMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMarcaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMarca);

        jMenuItemTelaInicial.setText("Tela Inicial");
        jMenuItemTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaInicialActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemTelaInicial);

        jMenuBar1.add(jMenuOpcoes);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocacaoActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeLocacao telaLocacao = new TelaDeLocacao();
            telaLocacao.setLocationRelativeTo(null);
            telaLocacao.setVisible(true);
            this.setVisible(false);
            telaLocacao.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemLocacaoActionPerformed

    private void jMenuItemCadastroDeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMotoristaActionPerformed
        // TODO add your handling code here:
        try {
            TelaCadastroMotorista telaMotorista = new TelaCadastroMotorista();
            telaMotorista.setLocationRelativeTo(null);
            telaMotorista.setVisible(true);
            this.setVisible(false);
            telaMotorista.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMotoristaActionPerformed

    private void jMenuItemCadastroDeCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeCategoriasActionPerformed
        // TODO add your handling code here:
        try {

            TelaDeCategoria telaCategoria = new TelaDeCategoria();
            telaCategoria.setLocationRelativeTo(null);
            telaCategoria.setVisible(true);
            this.setVisible(false);
            telaCategoria.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeCategoriasActionPerformed

    private void jMenuItemCadastroDeAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeAcessoriosActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeAcessorios telaAcessorios = new TelaDeAcessorios();
            telaAcessorios.setLocationRelativeTo(null);
            telaAcessorios.setVisible(true);
            this.setVisible(false);
            telaAcessorios.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeAcessoriosActionPerformed

    private void jMenuItemCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVeiculoActionPerformed
        // TODO add your handling code here:
        try {

            TelaCadastroVeiculo telaVeiculo = new TelaCadastroVeiculo();
            telaVeiculo.setLocationRelativeTo(null);
            telaVeiculo.setVisible(true);
            this.setVisible(false);
            telaVeiculo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroVeiculoActionPerformed

    private void jMenuItemCadastroDeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeClienteActionPerformed
        // TODO add your handling code here:
        try {

            TelaCadastroCliente cadastroCliente = new TelaCadastroCliente();
            cadastroCliente.setLocationRelativeTo(null);
            cadastroCliente.setVisible(true);
            this.setVisible(false);
            cadastroCliente.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeClienteActionPerformed

    private void jMenuItemCadastroDeModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeModeloActionPerformed
        // TODO add your handling code here:
        try {
            TelaDosModelos telaModelo = new TelaDosModelos();
            telaModelo.setLocationRelativeTo(null);
            telaModelo.setVisible(true);
            this.setVisible(false);
            telaModelo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeModeloActionPerformed

    private void jMenuItemCadastroDeMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMarcaActionPerformed
        // TODO add your handling code here:
        try {

            TelaDasMarcas telaMarca = new TelaDasMarcas();
            telaMarca.setLocationRelativeTo(null);
            telaMarca.setVisible(true);
            this.setVisible(false);
            telaMarca.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMarcaActionPerformed

    private void jMenuItemTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaInicialActionPerformed
        // TODO add your handling code here:
        try {

            TelaInicial telaInicial = new TelaInicial();
            telaInicial.setLocationRelativeTo(null);
            telaInicial.setVisible(true);
            this.setVisible(false);
            telaInicial.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemTelaInicialActionPerformed

    private void jCheckBoxLocacaoAMaisTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLocacaoAMaisTempoActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxLocacaoAMaisTempo.isSelected()) {
            jCheckBoxLocacaoAMenosTempo.setEnabled(false);
            jTextFieldDiasAMais.setEnabled(true);

        } else {
            jTextFieldDiasAMais.setText("");
            jTextFieldDiasAMais.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBoxLocacaoAMaisTempoActionPerformed

    private void jCheckBoxLocacaoAMenosTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLocacaoAMenosTempoActionPerformed
        if (jCheckBoxLocacaoAMenosTempo.isSelected()) {
            jCheckBoxLocacaoAMaisTempo.setEnabled(false);
            jTextFieldDiasAMenos.setEnabled(true);

        } else {
            jTextFieldDiasAMenos.setText("");
            jTextFieldDiasAMenos.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBoxLocacaoAMenosTempoActionPerformed

    private void jCheckBoxDanoSofridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDanoSofridoActionPerformed
        if (jCheckBoxDanoSofrido.isSelected()) {
            jTextFieldValorDano.setEnabled(true);

        } else {
            jTextFieldValorDano.setText("");
            jTextFieldValorDano.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBoxDanoSofridoActionPerformed

    private void jCheckBoxLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLimpezaActionPerformed
        if (jCheckBoxLimpeza.isSelected()) {
            jTextFieldValorSujo.setEnabled(true);

        } else {
            jTextFieldValorSujo.setText("");
            jTextFieldValorSujo.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBoxLimpezaActionPerformed

    private void jCheckBoxTanqueCheioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTanqueCheioActionPerformed
        if (jCheckBoxTanqueCheio.isSelected()) {
            jTextFieldTanqueCheio.setEnabled(true);

        } else {
            jTextFieldTanqueCheio.setText("");
            jTextFieldTanqueCheio.setEnabled(false);

        }
    }//GEN-LAST:event_jCheckBoxTanqueCheioActionPerformed

    private void jTextFieldValorDanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorDanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorDanoActionPerformed

    private void jTextFieldValorSujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorSujoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorSujoActionPerformed

    private void jTextFieldTanqueCheioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTanqueCheioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTanqueCheioActionPerformed

    private void jTextFieldHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        try {
            float multas = 0, quilometragemVeiculo = 0, valorTotal = 0, valorPorDia = 0;
            int dias = 0;
            String dataInicio, dataFim;
            SituacaoLocacao situacao;
            long diasCombinados = 0;
            if (jCheckBoxTanqueCheio.isSelected()) {
                multas += Float.parseFloat(jTextFieldTanqueCheio.getText());
            }
            if (jCheckBoxDanoSofrido.isSelected()) {
                multas += Float.parseFloat(jTextFieldValorDano.getText());
            }
            if (jCheckBoxLimpeza.isSelected()) {
                multas += Float.parseFloat(jTextFieldValorSujo.getText());
            }
            if (jCheckBoxLocacaoAMaisTempo.isSelected()) {
                dias += Integer.parseInt(jTextFieldDiasAMais.getText());
            }
            if (jCheckBoxLocacaoAMenosTempo.isSelected()) {
                dias += Integer.parseInt(jTextFieldDiasAMenos.getText()) * -1;
            }

            ArrayList<Locacao> listaVeiculo;
            listaVeiculo = locacaoControle.listagem();
            for (int i = 0; i < listaVeiculo.size(); i++) {
                if (jComboBoxLocacao.getSelectedItem().equals(listaVeiculo.get(i).getDataInicio())) {
                    int id = listaVeiculo.get(i).getId();
                    int idMotorista = listaVeiculo.get(i).getMotorista().getId();
                    int idVeiculo = listaVeiculo.get(i).getVeiculo().getId();
                    int idAcessorio = listaVeiculo.get(i).getAcessorio().getId();
                    quilometragemVeiculo = listaVeiculo.get(i).getVeiculo().getQuilometragem();
                    valorTotal = listaVeiculo.get(i).getValorDaLocação();
                    dataInicio = listaVeiculo.get(i).getDataInicio();
                    dataFim = listaVeiculo.get(i).getDataFim();
                    diasCombinados = listaVeiculo.get(i).getDiasLocados();
                    valorPorDia = listaVeiculo.get(i).getValorDia();

                }
            }
            //calculos
            float valorParam = valorTotal;
            diasCombinados = diasCombinados + dias;
            float valorAPagar = diasCombinados * valorPorDia;
            valorTotal = valorTotal - valorAPagar;
            if (multas != 0) {
                valorTotal = valorTotal - multas;
            }
            int idLocacao = 0;
            Devolucao objetoDevolucao = new Devolucao(0,locacaoControle.buscar(idLocacao), anexo1, anexo2, anexo3, anexo4, valorParam, valorPorDia, valorAPagar);
            ArrayList<Locacao> listaDevolucao = locacaoControle.listagem();
                for (int i = 0; i < listaDevolucao.size(); i++) {
                    if (jComboBoxLocacao.getSelectedItem().equals(listaDevolucao.get(i).getDataInicio())) {
                        objetoDevolucao.setLocacao(listaDevolucao.get(i));
                    }
                }
            devolucaoControle.incluir(objetoDevolucao);
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Falha ao carregar dados!");
        }
    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jTextFieldKmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKmKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldKmKeyTyped

    private void jTextFieldHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHoraKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldHoraKeyTyped

    private void jTextFieldDiasAMaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiasAMaisKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDiasAMaisKeyTyped

    private void jTextFieldDiasAMenosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiasAMenosKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDiasAMenosKeyTyped

    private void jTextFieldValorDanoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDanoKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldValorDanoKeyTyped

    private void jTextFieldValorSujoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorSujoKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldValorSujoKeyTyped

    private void jTextFieldTanqueCheioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTanqueCheioKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTanqueCheioKeyTyped

    private void jComboBoxLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLocacaoActionPerformed
        try {

            float quilometragemVeiculo = 0;
            float valorTotal = 0;

            ArrayList<Locacao> listaVeiculo;

            listaVeiculo = locacaoControle.listagem();
            for (int i = 0; i < listaVeiculo.size(); i++) {
                if (jComboBoxLocacao.getSelectedItem().equals(listaVeiculo.get(i).getDataInicio())) {
                    quilometragemVeiculo = listaVeiculo.get(i).getVeiculo().getQuilometragem();
                    valorTotal = listaVeiculo.get(i).getValorDaLocação();
                }
            }
            String saida = Float.toString(quilometragemVeiculo);
            jTextFieldKm.setText(saida);
            saida = Float.toString(valorTotal);
            jTextFieldTotal.setText(saida);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Falha ao carregar dados!");
        }
    }//GEN-LAST:event_jComboBoxLocacaoActionPerformed

    private void jButtonAnexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnexo1ActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            File logo = new File("./src/com/locadora/devolucao");
            fc.setCurrentDirectory(logo);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            String nome = arquivo.getName();
            String url = logo.getPath();
            url += "/" + nome;
            anexo1 = url;
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jTextFieldAnexo1.getWidth(), jTextFieldAnexo1.getHeight(), 1));
            jTextFieldAnexo1.setIcon(iconLogo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Selecione uma imagem!");
        }
    }//GEN-LAST:event_jButtonAnexo1ActionPerformed

    private void jButtonAnexo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnexo2ActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            File logo = new File("./src/com/locadora/devolucao");
            fc.setCurrentDirectory(logo);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            String nome = arquivo.getName();
            String url = logo.getPath();
            url += "/" + nome;
            anexo2 = url;
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jTextFieldAnexo2.getWidth(), jTextFieldAnexo2.getHeight(), 1));
            jTextFieldAnexo2.setIcon(iconLogo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Selecione uma imagem!");
        }
    }//GEN-LAST:event_jButtonAnexo2ActionPerformed

    private void jButtonAnexo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnexo3ActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            File logo = new File("./src/com/locadora/devolucao");
            fc.setCurrentDirectory(logo);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            String nome = arquivo.getName();
            String url = logo.getPath();
            url += "/" + nome;
            anexo3 = url;
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jTextFieldAnexo3.getWidth(), jTextFieldAnexo3.getHeight(), 1));
            jTextFieldAnexo3.setIcon(iconLogo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Selecione uma imagem!");
        }


    }//GEN-LAST:event_jButtonAnexo3ActionPerformed

    private void jButtonAnexo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnexo4ActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            File logo = new File("./src/com/locadora/devolucao");
            fc.setCurrentDirectory(logo);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            String nome = arquivo.getName();
            String url = logo.getPath();
            url += "/" + nome;
            anexo4 = url;
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jTextFieldAnexo4.getWidth(), jTextFieldAnexo4.getHeight(), 1));
            jTextFieldAnexo4.setIcon(iconLogo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Selecione uma imagem!");
        }
    }//GEN-LAST:event_jButtonAnexo4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnexo1;
    private javax.swing.JButton jButtonAnexo2;
    private javax.swing.JButton jButtonAnexo3;
    private javax.swing.JButton jButtonAnexo4;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JCheckBox jCheckBoxDanoSofrido;
    private javax.swing.JCheckBox jCheckBoxLimpeza;
    private javax.swing.JCheckBox jCheckBoxLocacaoAMaisTempo;
    private javax.swing.JCheckBox jCheckBoxLocacaoAMenosTempo;
    private javax.swing.JCheckBox jCheckBoxTanqueCheio;
    private javax.swing.JComboBox<String> jComboBoxLocacao;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroDeAcessorios;
    private javax.swing.JMenuItem jMenuItemCadastroDeCategorias;
    private javax.swing.JMenuItem jMenuItemCadastroDeCliente;
    private javax.swing.JMenuItem jMenuItemCadastroDeMarca;
    private javax.swing.JMenuItem jMenuItemCadastroDeModelo;
    private javax.swing.JMenuItem jMenuItemCadastroDeMotorista;
    private javax.swing.JMenuItem jMenuItemCadastroVeiculo;
    private javax.swing.JMenuItem jMenuItemLocacao;
    private javax.swing.JMenuItem jMenuItemTelaInicial;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTextFieldAnexo1;
    private javax.swing.JLabel jTextFieldAnexo2;
    private javax.swing.JLabel jTextFieldAnexo3;
    private javax.swing.JLabel jTextFieldAnexo4;
    private javax.swing.JTextField jTextFieldDiasAMais;
    private javax.swing.JTextField jTextFieldDiasAMenos;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldKm;
    private javax.swing.JTextField jTextFieldTanqueCheio;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldValorDano;
    private javax.swing.JTextField jTextFieldValorSujo;
    // End of variables declaration//GEN-END:variables
}
