/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.locagyn.visao;

import com.locagyn.controle.AcessoriosControle;
import com.locagyn.controle.ClienteControle;
import com.locagyn.controle.IAcessoriosControle;
import com.locagyn.controle.IClienteControle;
import com.locagyn.controle.ILocacaoControle;
import com.locagyn.controle.IMotoristaControle;
import com.locagyn.controle.IVeiculoControle;
import com.locagyn.controle.LocacaoControle;
import com.locagyn.controle.MotoristaControle;
import com.locagyn.controle.VeiculoControle;
import com.locagyn.enumeracao.TipoDeCliente;
import com.locagyn.modelos.Acessorios;
import com.locagyn.modelos.Cliente;
import com.locagyn.modelos.Motorista;
import com.locagyn.modelos.Veiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.locagyn.modelos.Locacao;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.locagyn.enumeracao.SituacaoLocacao;
import java.time.Duration;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.time.temporal.Temporal;
import java.util.Calendar;
import java.util.Date;
import java.time.temporal.Temporal;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emill
 */
public class TelaDeLocacao extends javax.swing.JFrame {

    IVeiculoControle veiculoControle = new VeiculoControle();
    IClienteControle clienteControle = new ClienteControle();
    IMotoristaControle motoristaControle = new MotoristaControle();
    IAcessoriosControle acessoriosControle = new AcessoriosControle();
    ILocacaoControle locacaoControle = new LocacaoControle();
    SimpleDateFormat dF = new SimpleDateFormat("yyyy-MM-dd");
    String dataInicioFormatada;
    String dataFimFormatada;
    long dias;
    LocalDate dFim;
    LocalDate dInicio;
    

    /**
     * Creates new form TelaDeLocacao
     */
    public TelaDeLocacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldIdentificador.setEnabled(false);
        jTextFieldValorDiaAcessorios.setEnabled(false);
        jTextFieldValorDiaVeiculo.setEnabled(false);
        jTextFieldValorTotalLocacao.setEnabled(false);
        jDateInicio.setDateFormatString("yyyy-MM-dd");
        jDateFim.setDateFormatString("yyyy-MM-dd");
        try {
            imprimirDadosNaGrid(locacaoControle.listagem());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);

        }

        try {
            ArrayList<Veiculo> listaVeiculo = veiculoControle.listagem();

            String[] listaCombo = new String[listaVeiculo.size()];
            for (int pos = 0; pos < listaVeiculo.size(); pos++) {
                listaCombo[pos] = listaVeiculo.get(pos).getPlaca();
                jComboBoxVeiculo.addItem(listaCombo[pos]);
            }

            ArrayList<Motorista> listaMotorista = motoristaControle.listagem();

            String[] listaMotora = new String[listaMotorista.size()];
            for (int pos = 0; pos < listaMotorista.size(); pos++) {
                listaMotora[pos] = listaMotorista.get(pos).getNome();
                jComboBoxMotorista.addItem(listaMotora[pos]);
            }

            ArrayList<Acessorios> lista = acessoriosControle.listagem();

            String[] listaAcessorio = new String[lista.size()];
            for (int pos = 0; pos < lista.size(); pos++) {
                listaAcessorio[pos] = lista.get(pos).getDescricao();
                jComboBoxAcessorios.addItem(listaAcessorio[pos]);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha ao carregar combobox. Verifique!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxVeiculo = new javax.swing.JComboBox<>();
        jComboBoxAcessorios = new javax.swing.JComboBox<>();
        jComboBoxMotorista = new javax.swing.JComboBox<>();
        jComboBoxTipoDeCliente = new javax.swing.JComboBox<>();
        jTextFieldValorDiaVeiculo = new javax.swing.JTextField();
        jTextFieldValorDiaAcessorios = new javax.swing.JTextField();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jTextFieldValorTotalLocacao = new javax.swing.JTextField();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonDevolver = new javax.swing.JButton();
        jButtonLocar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLocacao = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jDateFim = new com.toedter.calendar.JDateChooser();
        jDateInicio = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemLocacao = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMotorista = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCategorias = new javax.swing.JMenuItem();
        jMenuItemCadastroDeAcessorios = new javax.swing.JMenuItem();
        jMenuItemCadastroVeiculo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCliente = new javax.swing.JMenuItem();
        jMenuItemCadastroDeModelo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMarca = new javax.swing.JMenuItem();
        jMenuItemTelaInicial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 198, 238));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Motorista:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Veiculo:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Acessorios:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Valor por dia:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valor por dia:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Data Fim:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Data inicio:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Valor da locação:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Situação:");

        jComboBoxVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVeiculoActionPerformed(evt);
            }
        });

        jComboBoxAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAcessoriosActionPerformed(evt);
            }
        });

        jComboBoxTipoDeCliente.setModel(new javax.swing.DefaultComboBoxModel(TipoDeCliente.values()));
        jComboBoxTipoDeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeClienteActionPerformed(evt);
            }
        });

        jTextFieldValorDiaVeiculo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldValorDiaVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorDiaVeiculoKeyTyped(evt);
            }
        });

        jTextFieldValorDiaAcessorios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldValorDiaAcessorios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorDiaAcessoriosKeyTyped(evt);
            }
        });

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(SituacaoLocacao.values()));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });

        jTextFieldValorTotalLocacao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextFieldIdentificador.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButtonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");

        jButtonDevolver.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDevolver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonDevolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jButtonLocar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLocar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonLocar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLocar.setText("Locar");
        jButtonLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocarActionPerformed(evt);
            }
        });

        jTableLocacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "MOTORISTA", "VEÍCULO - PLACA", "ACESSORIOS", "DATA INICIO", "DATA FIM", "VALOR DA LOCAÇÃO", "SITUAÇÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLocacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableLocacao.setGridColor(new java.awt.Color(0, 0, 0));
        jTableLocacao.setRowHeight(50);
        jTableLocacao.setShowGrid(true);
        jTableLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocacaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLocacao);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tipo de Cliente:");

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValorDiaVeiculo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(jDateInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(91, 91, 91))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxTipoDeCliente, 0, 175, Short.MAX_VALUE)
                            .addComponent(jTextFieldValorTotalLocacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAcessorios, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE)
                            .addComponent(jComboBoxMotorista, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE)
                            .addComponent(jTextFieldValorDiaAcessorios, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDevolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxTipoDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldValorDiaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorDiaAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jDateFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldValorTotalLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonDevolver)
                    .addComponent(jButtonLocar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jMenuOpcoes.setText("Options");

        jMenuItemLocacao.setText("Locação");
        jMenuItemLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocacaoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemLocacao);

        jMenuItemCadastroDeMotorista.setText("Cadastro de Motorista");
        jMenuItemCadastroDeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMotoristaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMotorista);

        jMenuItemCadastroDeCategorias.setText("Cadastro de Categorias");
        jMenuItemCadastroDeCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeCategoriasActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCategorias);

        jMenuItemCadastroDeAcessorios.setText("Cadastro de Acessorios");
        jMenuItemCadastroDeAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeAcessoriosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeAcessorios);

        jMenuItemCadastroVeiculo.setText("Cadastro de Veículo");
        jMenuItemCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVeiculoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroVeiculo);

        jMenuItemCadastroDeCliente.setText("Cadastro de Cliente");
        jMenuItemCadastroDeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeClienteActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCliente);

        jMenuItemCadastroDeModelo.setText("Cadastro de Modelo");
        jMenuItemCadastroDeModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeModeloActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeModelo);

        jMenuItemCadastroDeMarca.setText("Cadastro de Marca");
        jMenuItemCadastroDeMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMarcaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMarca);

        jMenuItemTelaInicial.setText("Tela Inicial");
        jMenuItemTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaInicialActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemTelaInicial);

        jMenuBar1.add(jMenuOpcoes);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVeiculoActionPerformed
        // TODO add your handling code here:
        try {

            TelaCadastroVeiculo telaVeiculo = new TelaCadastroVeiculo();
            telaVeiculo.setLocationRelativeTo(null);
            telaVeiculo.setVisible(true);
            this.setVisible(false);
            telaVeiculo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroVeiculoActionPerformed

    private void jMenuItemCadastroDeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeClienteActionPerformed
        // TODO add your handling code here:
        try {

            TelaCadastroCliente cadastroCliente = new TelaCadastroCliente();
            cadastroCliente.setLocationRelativeTo(null);
            cadastroCliente.setVisible(true);
            this.setVisible(false);
            cadastroCliente.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeClienteActionPerformed

    private void jMenuItemCadastroDeModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeModeloActionPerformed
        // TODO add your handling code here:
        try {
            TelaDosModelos telaModelo = new TelaDosModelos();
            telaModelo.setLocationRelativeTo(null);
            telaModelo.setVisible(true);
            this.setVisible(false);
            telaModelo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeModeloActionPerformed

    private void jMenuItemCadastroDeMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMarcaActionPerformed
        // TODO add your handling code here:
        try {

            TelaDasMarcas telaMarca = new TelaDasMarcas();
            telaMarca.setLocationRelativeTo(null);
            telaMarca.setVisible(true);
            this.setVisible(false);
            telaMarca.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMarcaActionPerformed

    private void jMenuItemTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaInicialActionPerformed
        // TODO add your handling code here:
        try {

            TelaInicial telaInicial = new TelaInicial();
            telaInicial.setLocationRelativeTo(null);
            telaInicial.setVisible(true);
            this.setVisible(false);
            telaInicial.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemTelaInicialActionPerformed

    private void jComboBoxTipoDeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeClienteActionPerformed
        try {

            if (jComboBoxTipoDeCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {
                jComboBoxCliente.removeAllItems();
                ArrayList<Cliente> listaPessoaFisica = clienteControle.listagem(TipoDeCliente.PESSOA_FISICA);
                String[] listaPF = new String[listaPessoaFisica.size()];
                for (int pos = 0; pos < listaPessoaFisica.size(); pos++) {
                    listaPF[pos] = listaPessoaFisica.get(pos).getNome();
                    jComboBoxCliente.addItem(listaPF[pos]);
                }
            }
            if (jComboBoxTipoDeCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_JURIDICA)) {
                jComboBoxCliente.removeAllItems();
                ArrayList<Cliente> listaPessoaJuridica = clienteControle.listagem(TipoDeCliente.PESSOA_JURIDICA);
                String[] listaPJ = new String[listaPessoaJuridica.size()];
                for (int pos = 0; pos < listaPessoaJuridica.size(); pos++) {
                    listaPJ[pos] = listaPessoaJuridica.get(pos).getRazaoSocial();
                    jComboBoxCliente.addItem(listaPJ[pos]);
                }
            }
            if (jComboBoxTipoDeCliente.getSelectedItem().equals(TipoDeCliente.SELECIONE)) {
                jComboBoxCliente.removeAllItems();
            }

        } catch (Exception ex) {
            Logger.getLogger(TelaDeLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxTipoDeClienteActionPerformed

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    private void jMenuItemCadastroDeCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeCategoriasActionPerformed
        // TODO add your handling code here:
        try {

            TelaDeCategoria telaCategoria = new TelaDeCategoria();
            telaCategoria.setLocationRelativeTo(null);
            telaCategoria.setVisible(true);
            this.setVisible(false);
            telaCategoria.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeCategoriasActionPerformed

    private void jMenuItemCadastroDeAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeAcessoriosActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeAcessorios telaAcessorios = new TelaDeAcessorios();
            telaAcessorios.setLocationRelativeTo(null);
            telaAcessorios.setVisible(true);
            this.setVisible(false);
            telaAcessorios.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeAcessoriosActionPerformed

    private void jMenuItemCadastroDeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMotoristaActionPerformed
        // TODO add your handling code here:
        try {
            TelaCadastroMotorista telaMotorista = new TelaCadastroMotorista();
            telaMotorista.setLocationRelativeTo(null);
            telaMotorista.setVisible(true);
            this.setVisible(false);
            telaMotorista.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMotoristaActionPerformed

    private void jMenuItemLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocacaoActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeLocacao telaLocacao = new TelaDeLocacao();
            telaLocacao.setLocationRelativeTo(null);
            telaLocacao.setVisible(true);
            this.setVisible(false);
            telaLocacao.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemLocacaoActionPerformed

    private void jTableLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocacaoMouseClicked
        // TODO add your handling code here:
        try {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jTableLocacaoMouseClicked

    private void jButtonLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocarActionPerformed
        // TODO add your handling code here:
        try {
            int idVeiculo = 0;
            int idCliente = 0;
            int idMotorista = 0;
            int idAcessorio = 0;
            VeiculoControle veiculo = new VeiculoControle();
            ClienteControle cliente = new ClienteControle();
            MotoristaControle motorista = new MotoristaControle();
            AcessoriosControle acessorio = new AcessoriosControle();

            //trabalhando com datas
            SimpleDateFormat dataCalc = new SimpleDateFormat("yyyy-MM-dd");

            dataInicioFormatada = dataCalc.format(this.jDateInicio.getDate());
            dataFimFormatada = dataCalc.format(this.jDateFim.getDate());

            //calculos          
            dInicio = LocalDate.parse(dataInicioFormatada);

            dFim = LocalDate.parse(dataFimFormatada);

            dataInicioFormatada = dF.format(this.jDateInicio.getDate());
            dataFimFormatada = dF.format(this.jDateFim.getDate());

            Duration tempo = Duration.between(dInicio.atStartOfDay(), dFim.atStartOfDay());

            dias = tempo.toDays();
            long dias = tempo.toDays();
            
            //validar tempo para locar
            if(validaDataLocacao() == true){
             JOptionPane.showMessageDialog(null, "Veiculo Locado durante esse periodo!");  
             return;
            }
            
            
            
            
            
            float diariaVeiculo = Float.parseFloat(jTextFieldValorDiaVeiculo.getText());
            float diariaAcessorio = Float.parseFloat(jTextFieldValorDiaAcessorios.getText());

            float valorTotal = (diariaVeiculo * dias) + (diariaAcessorio * dias);

            float valorTotalCaucao = valorTotal + (valorTotal * (150 / 100));

            jTextFieldValorTotalLocacao.setText(valorTotalCaucao + "");
            float valorDia = Float.parseFloat(jTextFieldValorDiaAcessorios.getText()) + Float.parseFloat(jTextFieldValorDiaAcessorios.getText());

            //gravando dados
            if (jComboBoxTipoDeCliente.getSelectedItem().equals(TipoDeCliente.PESSOA_FISICA)) {
                Locacao objeto = new Locacao(0, cliente.buscar(idCliente, TipoDeCliente.PESSOA_FISICA), motorista.buscar(idMotorista), veiculo.buscar(idVeiculo), acessorio.buscar(idAcessorio), dataInicioFormatada, dataFimFormatada, valorTotalCaucao, jComboBoxSituacao.getSelectedItem(), dias, valorDia);
                ArrayList<Veiculo> listaVeiculo = veiculo.listagem();
                for (int i = 0; i < listaVeiculo.size(); i++) {
                    if (jComboBoxVeiculo.getSelectedItem().equals(listaVeiculo.get(i).getPlaca())) {
                        objeto.setVeiculo(listaVeiculo.get(i));
                    }
                }
                ArrayList<Cliente> listaCliente = cliente.listagem(TipoDeCliente.PESSOA_FISICA);
                for (int i = 0; i < listaCliente.size(); i++) {
                    if (jComboBoxCliente.getSelectedItem().equals(listaCliente.get(i).getNome())) {
                        objeto.setCliente(listaCliente.get(i));
                    }
                }
                ArrayList<Motorista> listaMotorista = motorista.listagem();
                for (int i = 0; i < listaMotorista.size(); i++) {
                    if (jComboBoxMotorista.getSelectedItem().equals(listaMotorista.get(i).getNome())) {
                        objeto.setMotorista(listaMotorista.get(i));
                    }
                }
                ArrayList<Acessorios> listaAcessorios = acessorio.listagem();
                for (int i = 0; i < listaAcessorios.size(); i++) {
                    if (jComboBoxAcessorios.getSelectedItem().equals(listaAcessorios.get(i).getDescricao())) {
                        objeto.setAcessorio(listaAcessorios.get(i));
                    }
                }
                locacaoControle.locar(objeto);

            } else {
                Locacao objeto = new Locacao(0, cliente.buscar(idCliente, TipoDeCliente.PESSOA_JURIDICA), motorista.buscar(idMotorista), veiculo.buscar(idVeiculo), acessorio.buscar(idAcessorio), dataInicioFormatada, dataFimFormatada, valorTotalCaucao, jComboBoxSituacao.getSelectedItem(), dias, valorDia);

                ArrayList<Veiculo> listaVeiculo = veiculo.listagem();
                for (int i = 0; i < listaVeiculo.size(); i++) {
                    if (jComboBoxVeiculo.getSelectedItem().equals(listaVeiculo.get(i).getPlaca())) {
                        objeto.setVeiculo(listaVeiculo.get(i));
                    }
                }
                ArrayList<Cliente> listaCliente = cliente.listagem(TipoDeCliente.PESSOA_JURIDICA);
                for (int i = 0; i < listaCliente.size(); i++) {
                    if (jComboBoxTipoDeCliente.getSelectedItem().equals(listaCliente.get(i).getRazaoSocial())) {
                        objeto.setCliente(listaCliente.get(i));
                    }
                }
                ArrayList<Motorista> listaMotorista = motorista.listagem();
                for (int i = 0; i < listaMotorista.size(); i++) {
                    if (jComboBoxMotorista.getSelectedItem().equals(listaMotorista.get(i).getNome())) {
                        objeto.setMotorista(listaMotorista.get(i));
                    }
                }
                ArrayList<Acessorios> listaAcessorios = acessorio.listagem();
                for (int i = 0; i < listaAcessorios.size(); i++) {
                    if (jComboBoxAcessorios.getSelectedItem().equals(listaAcessorios.get(i).getDescricao())) {
                        objeto.setAcessorio(listaAcessorios.get(i));
                    }
                }
                locacaoControle.locar(objeto);
                imprimirDadosNaGrid(locacaoControle.listagem());

            }

        } catch (Exception ex) {
            Logger.getLogger(TelaDeLocacao.class.getName()).log(Level.SEVERE, null, ex);

        }


    }//GEN-LAST:event_jButtonLocarActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        // TODO add your handling code here:
        try {
            TelaDevolucao telaDevolucao = new TelaDevolucao();
            telaDevolucao.setLocationRelativeTo(null);
            telaDevolucao.setVisible(true);
            this.setVisible(false);
            telaDevolucao.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }

    private void imprimirDadosNaGrid(ArrayList<Locacao> listaDeLocacao) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableLocacao.getModel();
            //Limpa a tabela
            model.setNumRows(0);
            Iterator<Locacao> lista = listaDeLocacao.iterator();
            while (lista.hasNext()) {
                String[] saida = new String[8];
                Locacao aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = motoristaControle.buscar(aux.getMotorista().getId()).getNome();
                saida[2] = veiculoControle.buscar(aux.getVeiculo().getId()).getPlaca();
                saida[3] = acessoriosControle.buscar(aux.getAcessorio().getId()).getDescricao();
                saida[4] = aux.getDataInicio().toString();
                saida[5] = aux.getDataFim().toString();
                saida[6] = aux.getValorDaLocação().toString();
                saida[7] = aux.getSituacao().toString();
                //Incluir nova linha na Tabela
                model.addRow(saida);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jTextFieldValorDiaVeiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDiaVeiculoKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldValorDiaVeiculoKeyTyped

    private void jTextFieldValorDiaAcessoriosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDiaAcessoriosKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldValorDiaAcessoriosKeyTyped

    private void jComboBoxVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVeiculoActionPerformed
        try {

            float valorDiaVeiculo = 0;

            ArrayList<Veiculo> listaVeiculo;

            listaVeiculo = veiculoControle.listagem();
            for (int i = 0; i < listaVeiculo.size(); i++) {
                if (jComboBoxVeiculo.getSelectedItem().equals(listaVeiculo.get(i).getPlaca())) {
                    valorDiaVeiculo = listaVeiculo.get(i).getCategoria().getValorDaLocacao();
                }
            }

            String saida = Float.toString(valorDiaVeiculo);
            jTextFieldValorDiaVeiculo.setText(saida);
            System.out.println(valorDiaVeiculo);
        } catch (Exception ex) {
            Logger.getLogger(TelaDeLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jComboBoxVeiculoActionPerformed

    private void jComboBoxAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAcessoriosActionPerformed
        try {

            float valorDiaAcessorio = 0;

            ArrayList<Acessorios> listaAcessorio;

            listaAcessorio = acessoriosControle.listagem();
            for (int i = 0; i < listaAcessorio.size(); i++) {
                if (jComboBoxAcessorios.getSelectedItem().equals(listaAcessorio.get(i).getDescricao())) {
                    valorDiaAcessorio = listaAcessorio.get(i).getValorDaLocacao();
                }
            }

            String saida = Float.toString(valorDiaAcessorio);
            jTextFieldValorDiaAcessorios.setText(saida);
            System.out.println(valorDiaAcessorio);
        } catch (Exception ex) {
            Logger.getLogger(TelaDeLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jComboBoxAcessoriosActionPerformed

    public boolean validaDataLocacao() {
        try {
            ArrayList<Locacao> listaLocacao = locacaoControle.listagem();
            Iterator<Locacao> lista = listaLocacao.iterator();
            if(lista.hasNext()){
                int i=Math.toIntExact(dias);
                long dia= dias;
                dataInicioFormatada = dF.format(this.jDateInicio.getDate());
                LocalDate data = dInicio;
                String[] dados = new String[8];
                Locacao aux = lista.next();
                dados[0] = aux.getId() + "";
                dados[4] = aux.getDataInicio().toString();
                dados[5] = aux.getDataFim().toString();
                for(i=(int) dias;i<=dias;i--){
                    dia = (long) i;
                    LocalDate proximoDia = data.plusDays(dia);
                    if(proximoDia == dInicio || proximoDia == dFim){
                        return true;
                    }
                }
            } 
        } catch (Exception ex) {
            Logger.getLogger(TelaDeLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JButton jButtonLocar;
    private javax.swing.JComboBox<String> jComboBoxAcessorios;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxMotorista;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JComboBox<String> jComboBoxTipoDeCliente;
    private javax.swing.JComboBox<String> jComboBoxVeiculo;
    private com.toedter.calendar.JDateChooser jDateFim;
    private com.toedter.calendar.JDateChooser jDateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroDeAcessorios;
    private javax.swing.JMenuItem jMenuItemCadastroDeCategorias;
    private javax.swing.JMenuItem jMenuItemCadastroDeCliente;
    private javax.swing.JMenuItem jMenuItemCadastroDeMarca;
    private javax.swing.JMenuItem jMenuItemCadastroDeModelo;
    private javax.swing.JMenuItem jMenuItemCadastroDeMotorista;
    private javax.swing.JMenuItem jMenuItemCadastroVeiculo;
    private javax.swing.JMenuItem jMenuItemLocacao;
    private javax.swing.JMenuItem jMenuItemTelaInicial;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLocacao;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldValorDiaAcessorios;
    private javax.swing.JTextField jTextFieldValorDiaVeiculo;
    private javax.swing.JTextField jTextFieldValorTotalLocacao;
    // End of variables declaration//GEN-END:variables
}
